#pragma once

#define PLF_SKIPLIST_VERSION_MAJOR 0
#define PLF_SKIPLIST_VERSION_MINOR 1
#define PLF_SKIPLIST_VERSION_PATCH 0
#define PLF_SKIPLIST_VERSION \
  (PLF_SKIPLIST_VERSION_MAJOR * 10000 + PLF_SKIPLIST_VERSION_MINOR * 100 + PLF_SKIPLIST_VERSION_PATCH)
